# Generated by Django 2.2.3 on 2019-07-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifpy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='rules',
            field=models.ManyToManyField(blank=True, to='notifpy.Channel'),
        ),
    ]
