# Generated by Django 2.2.3 on 2019-07-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifpy', '0002_auto_20190703_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='priority',
            field=models.IntegerField(choices=[(-1, 'None'), (0, 'Low'), (1, 'Medium'), (2, 'High')], default=1),
        ),
    ]
