# Generated by Django 3.1 on 2021-01-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifpy', '0007_subscriptionhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='twitch',
            field=models.ManyToManyField(blank=True, to='notifpy.TwitchUser'),
        ),
        migrations.AlterField(
            model_name='subscriptionhistory',
            name='youtube',
            field=models.ManyToManyField(blank=True, to='notifpy.YoutubeChannel'),
        ),
    ]
